name: Docker run

on:
  push:
    branches:
      - main

jobs:
  build-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build
      - name: Run Redis
        run: docker-compose run -d --name my-redis redis
      - name: Run App
        run: docker-compose run app
